export const GET_PODUCTS = 'GET_PODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_BY_NAME = 'GET_PRODUCT_BY_NAME';
export const DESTROY_PREDICTIONS = 'DESTROY_PREDICTIONS';
