export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
export const GET_PRODUCTS_BY_NAME = 'GET_PRODUCTS_BY_NAME'
export const DESTROY_PREDICTIONS = 'DESTROY_PREDICTIONS';
export const SEARCH_PRODUCTS_BY_NAME = 'SEARCH_PRODUCTS_BY_NAME';

